font_family Share Tech Mono
font_size 14.0

cursor_shape underline
cursor_underline_thickness 2.0
cursor #5fff00
cursor_blink_interval 0.7
shell_integration no-cursor

scrollback_lines 10000
scrollbar always
scrollbar_interactive yes
scrollbar_jump_on_click yes
scrollbar_width 0.5
scrollbar_hover_width 1
scrollbar_handle_opacity 0.5
scrollbar_gap 0.1

mouse_hide_wait 3.0

copy_on_select clipboard

enable_audio_bell no
